server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  server:
    # 서버가 요청을 받기 전 대기할 초기 시간(ms)
    # 모든 서비스가 등록 되길 기다리기 위해 5분 후 정보를 공유
    wait-time-in-ms-when-sync-empty: 300000

management:
  endpoints:
    web:
      exposure:
        include: "*"